# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ylabonte
    commit-message:
      prefix: "ci"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - ylabonte
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
    groups:
      dev-tools:
        patterns:
          - "ruff"
          - "mypy"
          - "pre-commit"
          - "pytest*"
          - "pytest-*"
          - "aioresponses"
          - "pytest-freezer"