name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "Breaking Changes"
    label: "breaking"
  - title: "New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "Bug Fixes"
    label: "fix"
  - title: "Dependency Updates"
    label: "dependencies"
  - title: "Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "docs"

change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "fix"
      - "dependencies"
      - "chore"
      - "refactor"
      - "docs"
  default: patch

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/ylabonte/proconip-hass/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
